### ISSUE TITLE
Imagebot  error debugger

### ISSUE THREAD

**Issue by K1nK0ng69** [K1nK0ng69/II-imagebot#1]
I can't start Python Debugger, because I have error in my code and I can't do anything:

Fatal Python error: init_import_site: Failed to import the site module
Python runtime state: initialized
Traceback (most recent call last):
  File "C:\Users\Иван\AppData\Local\Programs\Python\Python39\lib\site.py", line 589, in <module>
    main()
  File "C:\Users\Иван\AppData\Local\Programs\Python\Python39\lib\site.py", line 572, in main
    known_paths = venv(known_paths)
  File "C:\Users\Иван\AppData\Local\Programs\Python\Python39\lib\site.py", line 504, in venv
    addsitepackages(known_paths, [sys.prefix])
  File "C:\Users\Иван\AppData\Local\Programs\Python\Python39\lib\site.py", line 359, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "C:\Users\Иван\AppData\Local\Programs\Python\Python39\lib\site.py", line 208, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "C:\Users\Иван\AppData\Local\Programs\Python\Python39\lib\site.py", line 164, in addpackage
    for n, line in enumerate(f):
  File "C:\Users\Иван\AppData\Local\Programs\Python\Python39\lib\encodings\cp1251.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 2143: character maps to <undefined>

Process finished with exit code 1

What should I do?

**Comment by K1nK0ng69** [comment]
Please help!
